Access to Electricity
========================================================


Create table of population for each region / income level combination
```{r}
library(jsonlite)
library(dplyr)
library(tidyr)
populationUrl <- 'http://api.worldbank.org/countries/indicators/SP.POP.TOTL?per_page=1000&date=2013&format=json'
savedFile <- "/Users/jamesmungall/MyR/GettingCleaningData/data/worldBank/population/population.json"
download.file(populationUrl, destfile = savedFile, method = "curl")
jsonData <- fromJSON(savedFile)
population <- jsonData[[2]][-(1:34),]
population <- population %>% flatten() %>% tbl_df() %>% select(country.value,pop=value)
View(population)
```

```{r}
url <- 'http://api.worldbank.org/countries?format=json&per_page=1000'
savedFile <- "/Users/jamesmungall/MyR/GettingCleaningData/data/worldBank/countries.json"
download.file(url, destfile = savedFile, method = "curl")
jsonData <- fromJSON(savedFile)
countries <- jsonData[[2]] %>% flatten() %>% tbl_df() %>% select(country.value=name,region.id,incomeLevel.id)
View(countries)
```

combine data
```{r}
popRegionIncome <- left_join(population,countries)
popRegionIncomeTable <- popRegionIncome %>% group_by(region.id,incomeLevel.id) %>% summarise(totals =sum(as.numeric(pop)))%>% spread(key=region.id,value=totals)


popRegionIncomeTable[is.na(popRegionIncomeTable)] <- 0; # convert NAs to zeros
View(format(popRegionIncomeTable,digits=1))
```

Turn electricity percentages into number of persons
```{r}

url<-'http://api.worldbank.org/countries/indicators/EG.ELC.ACCS.ZS?per_page=1000&date=2010&format=json'
savedFile <- "/Users/jamesmungall/MyR/GettingCleaningData/data/worldBank/accessToElectricity/accessToElectricity.json"
download.file(url, destfile = savedFile, method = "curl")
jsonData <- fromJSON(savedFile)
accessToElectricity <- jsonData[[2]]
View(accessToElectricity)
```

